name = "Modpack Complicatedcraft"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5f1e4e29c531b5a71ec12d9aadce93c3dcd8c6fa734d5487c46b2e9a336989b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
