name = "Modpack Complicatedcraft"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9bbd5f4f8da0ca48db75ec092eea9a94c1d8d3e7585bc6aa1886d5ac8153732"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
