name = "Modpack Complicatedcraft"
author = "PGSCOM"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "884f8ba9884b44b58ec6cd64eb67a746b169f4a7df09e750ca47cf3cdb098012"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
